---
# tasks file for node_exporter
  - name: Dependonsi Debian
    block:
      - name: Install dependonsi
        apt: 
          name:
          - curl
          state: latest
    when: ansible_os_family == "Debian"

  - name: Dependonsi RedHat
    block:
      - name: Install dependonsi
        yum:
          name:
          - curl
          state: latest
    when: ansible_os_family == "RedHat"

  - name: Creates directory
    file:
      path: "{{item }}"
      state: directory
    loop:
      - "/opt/xmrig"

  - name: Determine latest GitHub release (local)
    delegate_to: localhost
    become: false
    uri:
      url: "https://api.github.com/repos/MoneroOcean/xmrig/releases"
      body_format: json
    register: _github_releases
    until: _github_releases.status == 200
    retries: 5

  - name: Set verison
    set_fact:
      xmrig_version: "{{ _github_releases.json.0.tag_name }}"

  - name: Generate update script
    template:
       src: xmrig.j2
       dest: "/opt/xmrig/xmrig.sh"
       mode: a+x
    notify: Install/Update xmrig
